name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    strategy:
      matrix:
        py:
          - '3.11-dev'
        attempts:
          - 1
          - 2
          - 3
          - 4
          - 5

      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}

    #- name: Get pip cache dir
    #  id: pip-cache
    #  run: |
    #    echo "::set-output name=dir::$(pip cache dir)"    # - name: Cache

    #- name: Cache PyPI
    #  uses: actions/cache@v2.1.7
    #  with:
    #    key: pip-ci-${{ runner.os }}-${{ matrix.py }}
    #    path: ${{ steps.pip-cache.outputs.dir }}

    - name: Install dependencies
      run: |
        python -m pip install coverage==6.3

    - name: Install aiomysql
      run: |
        python -m pip install .

    #- name: Try simple socket connection in asyncio
    #  run: |
    #    coverage run simple-test.py
    #  env:
    #    PYTHONUNBUFFERED: 1

    - name: Test without coverage
      run: |
        python aiomysql-sockettest.py
      env:
        PYTHONUNBUFFERED: 1

    - name: Test with coverage
      run: |
        coverage run atest.py
      env:
        PYTHONUNBUFFERED: 1
