name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        attempt:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.11-dev'

    - name: Install coverage.py
      run: |
        python -m pip install coverage==6.3


    - name: Try simple socket connection
      run: |
        for i in $(seq 60)
        do
            echo attempt $i
            coverage run simple-test.py
        done
